[package]
name = "cudb"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
bincode = "1.3.3"
byteorder = "1.1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
rand = "0.8.4"
